### ISSUE TITLE
Add Usage

### ISSUE THREAD

**Issue by Rastapar** [nusnlp/greco#3]
Could you add a section of Usage please? It is unclear how it corrects grammatical errors in a sentence.

**Comment by mrqorib** [comment]
Hi @Rastapar, GRECO is a quality estimation model (producing a grammaticality score) that can be used to combine multiple grammatical error correction (GEC) models. You need to get the outputs of other GEC systems first to use GRECO to correct grammatical errors. Some open-source ones that you can use are [GECToR](https://github.com/grammarly/gector), [GECToR Large](https://github.com/MaksTarnavskyi/gector-large), [BART](https://github.com/Katsumata420/generic-pretrained-GEC) and T5 ([JohnSnow Lab](https://sparknlp.org/2022/01/12/t5_grammar_error_corrector_en.html), [vennify](https://huggingface.co/vennify/t5-base-grammar-correction), [addy88](https://huggingface.co/addy88/t5-grammar-correction)).

**Comment by mrqorib** [comment]
Hi, I will close this issue for now. Feel free to reopen it if you still have questions or concerns.
